# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Development\Tactics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Development\Tactics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\msys64\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Development\Tactics\CMakeFiles D:\Development\Tactics\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Development\Tactics\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tactics-Server

# Build rule for target.
Tactics-Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Tactics-Server
.PHONY : Tactics-Server

# fast build rule for target.
Tactics-Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Server.dir\build.make CMakeFiles/Tactics-Server.dir/build
.PHONY : Tactics-Server/fast

#=============================================================================
# Target rules for targets named Tactics-Client

# Build rule for target.
Tactics-Client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Tactics-Client
.PHONY : Tactics-Client

# fast build rule for target.
Tactics-Client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Client.dir\build.make CMakeFiles/Tactics-Client.dir/build
.PHONY : Tactics-Client/fast

src/client/Client.obj: src/client/Client.cpp.obj
.PHONY : src/client/Client.obj

# target to build an object file
src/client/Client.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Client.dir\build.make CMakeFiles/Tactics-Client.dir/src/client/Client.cpp.obj
.PHONY : src/client/Client.cpp.obj

src/client/Client.i: src/client/Client.cpp.i
.PHONY : src/client/Client.i

# target to preprocess a source file
src/client/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Client.dir\build.make CMakeFiles/Tactics-Client.dir/src/client/Client.cpp.i
.PHONY : src/client/Client.cpp.i

src/client/Client.s: src/client/Client.cpp.s
.PHONY : src/client/Client.s

# target to generate assembly for a file
src/client/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Client.dir\build.make CMakeFiles/Tactics-Client.dir/src/client/Client.cpp.s
.PHONY : src/client/Client.cpp.s

src/client/main.obj: src/client/main.cpp.obj
.PHONY : src/client/main.obj

# target to build an object file
src/client/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Client.dir\build.make CMakeFiles/Tactics-Client.dir/src/client/main.cpp.obj
.PHONY : src/client/main.cpp.obj

src/client/main.i: src/client/main.cpp.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Client.dir\build.make CMakeFiles/Tactics-Client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Client.dir\build.make CMakeFiles/Tactics-Client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/server/Server.obj: src/server/Server.cpp.obj
.PHONY : src/server/Server.obj

# target to build an object file
src/server/Server.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Server.dir\build.make CMakeFiles/Tactics-Server.dir/src/server/Server.cpp.obj
.PHONY : src/server/Server.cpp.obj

src/server/Server.i: src/server/Server.cpp.i
.PHONY : src/server/Server.i

# target to preprocess a source file
src/server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Server.dir\build.make CMakeFiles/Tactics-Server.dir/src/server/Server.cpp.i
.PHONY : src/server/Server.cpp.i

src/server/Server.s: src/server/Server.cpp.s
.PHONY : src/server/Server.s

# target to generate assembly for a file
src/server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Server.dir\build.make CMakeFiles/Tactics-Server.dir/src/server/Server.cpp.s
.PHONY : src/server/Server.cpp.s

src/server/main.obj: src/server/main.cpp.obj
.PHONY : src/server/main.obj

# target to build an object file
src/server/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Server.dir\build.make CMakeFiles/Tactics-Server.dir/src/server/main.cpp.obj
.PHONY : src/server/main.cpp.obj

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Server.dir\build.make CMakeFiles/Tactics-Server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Tactics-Server.dir\build.make CMakeFiles/Tactics-Server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Tactics-Client
	@echo ... Tactics-Server
	@echo ... src/client/Client.obj
	@echo ... src/client/Client.i
	@echo ... src/client/Client.s
	@echo ... src/client/main.obj
	@echo ... src/client/main.i
	@echo ... src/client/main.s
	@echo ... src/server/Server.obj
	@echo ... src/server/Server.i
	@echo ... src/server/Server.s
	@echo ... src/server/main.obj
	@echo ... src/server/main.i
	@echo ... src/server/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

